[[redirects]]
  from = "/api/*"
  to = "http://13.201.62.152:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/:code([a-zA-Z0-9]{6,10})"
  to = "http://13.201.62.152:8080/:code"
  status = 302
  force = true

# React Router catch-all
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
