[[redirects]]
  from = "/api/*"
  to = "http://13.201.62.152:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/:shortcode"
  to = "http://13.201.62.152:8080/:shortcode"
  status = 302
  force = true

# React Router catch-all
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
